import os
import math
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

def generate_gcode():
    # Plate dimensions
    plate_w = 65.0
    plate_h = 85.0
    plate_t = 10.0
    
    # Tool definitions
    tool_d = 4.2
    tool_r = tool_d / 2.0
    
    # Process parameters
    spindle_speed = 8000
    feed_rate = 600
    plunge_rate = 200
    safe_z = 5.0
    start_z = 1.0
    stepdown = 0.5
    final_z = -10.5  # breakthrough
    
    gcode = []
    
    # Header
    gcode.append("%")
    gcode.append("O1001 ; Program number for FANUC")
    gcode.append("; CNC Machining G-Code (Iwashita NV2 / FANUC)")
    gcode.append("; Generated by Antigravity")
    gcode.append("; Plate Dimensions: 65mm x 85mm x 10mm")
    gcode.append(f"; Tool: Flat Endmill D = {tool_d}mm")
    gcode.append("; Material: Aluminum A5052")
    gcode.append("; Coordinate Origin G54: Bottom-Left Top Surface of Plate")
    gcode.append("")
    gcode.append("G21 G90 G17 G40 G49 G80 ; Safety block: Metric, Absolute, XY plane, Cancel comp/canned cycles")
    gcode.append("G54                     ; Select work coordinate system 1")
    gcode.append(f"M3 S{spindle_speed}       ; Spindle clockwise at {spindle_speed} RPM")
    gcode.append("M8                      ; Coolant ON")
    gcode.append(f"G0 Z{safe_z:.3f}            ; Rapid to safe Z height")
    gcode.append("")

    # --- 1. Central φ50mm Hole (Pocketing) ---
    gcode.append("; =================================================")
    gcode.append("; OPERATION 1: Central Hole (D = 50.0mm, Pocketing)")
    gcode.append("; =================================================")
    
    cx, cy = plate_w / 2.0, 47.15
    hole_d = 50.0
    hole_r = hole_d / 2.0
    max_tool_r = hole_r - tool_r  # Max toolpath center radius (22.9mm)
    
    # Stepover sequence (starting from center R=2.0 up to R=22.9)
    stepover_step = 2.0
    radii = list(np.arange(2.0, max_tool_r, stepover_step))
    if radii[-1] < max_tool_r:
        radii.append(max_tool_r)
        
    gcode.append(f"; Center: ({cx:.3f}, {cy:.3f}), Toolpath Max Radius: {max_tool_r:.3f}mm")
    gcode.append(f"; Concentric passes at radii: {', '.join([f'{r:.1f}' for r in radii])}")
    
    # Rapid to center above work
    gcode.append(f"G0 X{cx:.3f} Y{cy:.3f}")
    gcode.append(f"G0 Z{start_z:.3f}")
    
    z_depths = np.arange(-stepdown, final_z - 0.001, -stepdown)
    if z_depths[-1] > final_z:
        z_depths = np.append(z_depths, final_z)
        
    for z in z_depths:
        gcode.append(f"; --- Depth Z = {z:.3f}mm ---")
        # Plunge at center
        gcode.append(f"G1 Z{z:.3f} F{plunge_rate}")
        
        # Cut concentric circles
        for r in radii:
            # Feed out to radius along X-axis
            gcode.append(f"G1 X{cx + r:.3f} Y{cy:.3f} F{feed_rate}")
            # Circle counter-clockwise (climb milling)
            # Center of circle is at cx, cy. Vector from start (cx+r, cy) to center is (-r, 0)
            gcode.append(f"G3 X{cx + r:.3f} Y{cy:.3f} I{-r:.3f} J0.000 F{feed_rate}")
            
        # Return to center to prevent tool rubbing and clear path
        gcode.append(f"G1 X{cx:.3f} Y{cy:.3f} F{feed_rate}")
        
    gcode.append(f"G0 Z{safe_z:.3f} ; Retract tool")
    gcode.append("")

    # --- 2. M5 Holes (4箇所, φ4.2mm, Peck Drilling) ---
    gcode.append("; =================================================")
    gcode.append("; OPERATION 2: M5 Holes (4 places, D = 4.2mm, Peck Drilling)")
    gcode.append("; =================================================")
    
    m5_pitch = 50.0
    m5_holes = [
        (cx - m5_pitch/2.0, cy + m5_pitch/2.0),
        (cx + m5_pitch/2.0, cy + m5_pitch/2.0),
        (cx - m5_pitch/2.0, cy - m5_pitch/2.0),
        (cx + m5_pitch/2.0, cy - m5_pitch/2.0)
    ]
    
    peck_depths = [-1.0, -2.0, -3.0, -4.0, -5.0, -6.0, -7.0, -8.0, -9.0, -10.0, final_z]
    
    for idx, (hx, hy) in enumerate(m5_holes, 1):
        gcode.append(f"; Hole {idx}: ({hx:.3f}, {hy:.3f})")
        gcode.append(f"G0 X{hx:.3f} Y{hy:.3f}")
        gcode.append(f"G0 Z{start_z:.3f}")
        
        for p_idx, p_z in enumerate(peck_depths):
            if p_idx == 0:
                gcode.append(f"G1 Z{p_z:.3f} F{plunge_rate}")
            else:
                # Rapid to just above previous depth (0.2mm clearance)
                prev_z = peck_depths[p_idx-1]
                gcode.append(f"G0 Z{prev_z + 0.2:.3f}")
                gcode.append(f"G1 Z{p_z:.3f} F{plunge_rate}")
            
            # Retract to start Z to clear chips
            gcode.append(f"G0 Z{start_z:.3f}")
            
        gcode.append(f"G0 Z{safe_z:.3f} ; Retract to safe Z")
        gcode.append("")

    # --- 3. Bottom Holes (2箇所, φ5.5mm, Milling/Circular Interpolation) ---
    gcode.append("; =================================================")
    gcode.append("; OPERATION 3: Bottom Holes (2 places, D = 5.5mm, Milling)")
    gcode.append("; =================================================")
    
    bottom_hole_y = 8.25
    bottom_hole_pitch = 30.0
    bottom_hole_d = 5.5
    bottom_hole_r = bottom_hole_d / 2.0
    bottom_toolpath_r = bottom_hole_r - tool_r  # 2.75 - 2.1 = 0.65mm
    
    bottom_holes = [
        (cx - bottom_hole_pitch/2.0, bottom_hole_y),
        (cx + bottom_hole_pitch/2.0, bottom_hole_y)
    ]
    
    for idx, (bx, by) in enumerate(bottom_holes, 1):
        gcode.append(f"; Bottom Hole {idx}: ({bx:.3f}, {by:.3f})")
        gcode.append(f"G0 X{bx:.3f} Y{by:.3f}")
        gcode.append(f"G0 Z{start_z:.3f}")
        
        for z in z_depths:
            gcode.append(f"; --- Depth Z = {z:.3f}mm ---")
            # Plunge at center
            gcode.append(f"G1 Z{z:.3f} F{plunge_rate}")
            # Feed out to toolpath radius
            gcode.append(f"G1 X{bx + bottom_toolpath_r:.3f} Y{by:.3f} F{feed_rate}")
            # CCW circular interpolation
            gcode.append(f"G3 X{bx + bottom_toolpath_r:.3f} Y{by:.3f} I{-bottom_toolpath_r:.3f} J0.000 F{feed_rate}")
            # Feed back to center
            gcode.append(f"G1 X{bx:.3f} Y{by:.3f} F{feed_rate}")
            
        gcode.append(f"G0 Z{safe_z:.3f} ; Retract tool")
        gcode.append("")
        
    # Footer
    gcode.append("; End of Program")
    gcode.append("M9            ; Coolant OFF")
    gcode.append("M5            ; Spindle OFF")
    gcode.append("G91 G28 Z0.0  ; Retract Z to machine reference home position")
    gcode.append("G28 X0.0 Y0.0 ; Retract X and Y to machine reference home position")
    gcode.append("G90           ; Switch back to absolute coordinates")
    gcode.append("M30           ; Program end and rewind")
    gcode.append("%")
    
    # Save G-Code file
    file_path = "plate_machining.gcode"
    with open(file_path, "w") as f:
        f.write("\n".join(gcode))
        
    print(f"G-code successfully written to {file_path}")
    return file_path

def parse_gcode_and_plot(gcode_file, image_path):
    # Lists to store path segments
    # Each segment is (type, xs, ys, zs) where type is 'G0' (rapid) or 'G1/2/3' (feed)
    segments = []
    
    # State variables
    curr_x = 0.0
    curr_y = 0.0
    curr_z = 0.0
    
    # Parse G-code line by line
    with open(gcode_file, 'r') as f:
        lines = f.readlines()
        
    for line in lines:
        # Strip comments
        line_clean = line.split(';')[0].split('(')[0].strip()
        if not line_clean or line_clean.startswith('%') or line_clean.upper().startswith('O') or 'G28' in line_clean.upper():
            continue
            
        tokens = line_clean.upper().split()
        cmd = None
        for t in tokens:
            if t.startswith('G'):
                try:
                    cmd_val = int(t[1:])
                    if cmd_val in [0, 1, 2, 3]:
                        cmd = cmd_val
                except ValueError:
                    pass
                    
        # Parse coordinates
        new_x = curr_x
        new_y = curr_y
        new_z = curr_z
        i_val = 0.0
        j_val = 0.0
        
        has_xyz = False
        has_ij = False
        
        for t in tokens:
            if t.startswith('X'):
                new_x = float(t[1:])
                has_xyz = True
            elif t.startswith('Y'):
                new_y = float(t[1:])
                has_xyz = True
            elif t.startswith('Z'):
                new_z = float(t[1:])
                has_xyz = True
            elif t.startswith('I'):
                i_val = float(t[1:])
                has_ij = True
            elif t.startswith('J'):
                j_val = float(t[1:])
                has_ij = True
                
        # If cmd is not specified, it inherits the previous modal motion code (G0/G1/G2/G3)
        # But we must be careful. Let's see if tokens start with X, Y, Z or are G commands.
        # Let's set cmd based on what was in the line or assume modal G1 if X/Y/Z is present and we had a modal command.
        # To be safe, let's track the modal motion command:
        if cmd is not None:
            parse_gcode_and_plot.modal_cmd = cmd
        elif has_xyz:
            cmd = getattr(parse_gcode_and_plot, 'modal_cmd', 1)
            
        if cmd is None:
            continue
            
        if cmd == 0:  # Rapid linear
            segments.append(('G0', [curr_x, new_x], [curr_y, new_y], [curr_z, new_z]))
            curr_x, curr_y, curr_z = new_x, new_y, new_z
        elif cmd == 1:  # Feed linear
            segments.append(('G1', [curr_x, new_x], [curr_y, new_y], [curr_z, new_z]))
            curr_x, curr_y, curr_z = new_x, new_y, new_z
        elif cmd in [2, 3]:  # CW / CCW circular interpolation
            # Calculate arc center
            cx = curr_x + i_val
            cy = curr_y + j_val
            r = math.sqrt(i_val**2 + j_val**2)
            
            # Start and end angles
            theta_start = math.atan2(curr_y - cy, curr_x - cx)
            theta_end = math.atan2(new_y - cy, new_x - cx)
            
            # Check for full circle
            if abs(curr_x - new_x) < 1e-4 and abs(curr_y - new_y) < 1e-4:
                # Full circle
                if cmd == 3:  # CCW
                    theta_end = theta_start + 2.0 * math.pi
                else:         # CW
                    theta_end = theta_start - 2.0 * math.pi
            else:
                # Partial arc
                if cmd == 3:  # CCW
                    if theta_end <= theta_start:
                        theta_end += 2.0 * math.pi
                else:         # CW
                    if theta_end >= theta_start:
                        theta_end -= 2.0 * math.pi
            
            # Interpolate arc
            num_points = 40
            theta_pts = np.linspace(theta_start, theta_end, num_points)
            xs = cx + r * np.cos(theta_pts)
            ys = cy + r * np.sin(theta_pts)
            zs = np.linspace(curr_z, new_z, num_points)
            
            segments.append((f'G{cmd}', xs, ys, zs))
            curr_x, curr_y, curr_z = new_x, new_y, new_z

    # Plotting using matplotlib 3D
    fig = plt.figure(figsize=(10, 8), dpi=150)
    ax = fig.add_subplot(111, projection='3d')
    
    # 1. Draw Stock Boundary (Wireframe of 65x85x10mm plate)
    pw, ph, pt = 65.0, 85.0, 10.0
    safe_z = 5.0
    # Vertices of the box
    corners = np.array([
        [0, 0, 0], [pw, 0, 0], [pw, ph, 0], [0, ph, 0],  # Top face (Z=0)
        [0, 0, -pt], [pw, 0, -pt], [pw, ph, -pt], [0, ph, -pt]  # Bottom face (Z=-10)
    ])
    
    # Draw top face outline
    ax.plot([0, pw, pw, 0, 0], [0, 0, ph, ph, 0], [0, 0, 0, 0, 0], color='gray', linestyle='--', alpha=0.7, label='Stock Outline (65x85x10mm)')
    # Draw bottom face outline
    ax.plot([0, pw, pw, 0, 0], [0, 0, ph, ph, 0], [-pt, -pt, -pt, -pt, -pt], color='gray', linestyle='--', alpha=0.5)
    # Vertical corners
    for i in range(4):
        ax.plot([corners[i, 0], corners[i+4, 0]], [corners[i, 1], corners[i+4, 1]], [corners[i, 2], corners[i+4, 2]], color='gray', linestyle='--', alpha=0.5)

    # 2. Draw Toolpaths
    g0_plotted = False
    g1_plotted = False
    
    for seg_type, xs, ys, zs in segments:
        if seg_type == 'G0':
            # Rapid transitions
            line, = ax.plot(xs, ys, zs, color='red', linestyle=':', linewidth=1.0, alpha=0.6)
            if not g0_plotted:
                line.set_label('Rapid Move (G0)')
                g0_plotted = True
        else:
            # Feed cuts (G1, G2, G3)
            line, = ax.plot(xs, ys, zs, color='#1f77b4', linestyle='-', linewidth=1.5, alpha=0.8)
            if not g1_plotted:
                line.set_label('Cutting Feed (G1/G2/G3)')
                g1_plotted = True

    # Graph annotations
    ax.set_title('CNC Toolpath 3D Trajectory (4.2mm Endmill)', fontsize=14, fontweight='bold', pad=20)
    ax.set_xlabel('X (mm)', fontsize=10, labelpad=10)
    ax.set_ylabel('Y (mm)', fontsize=10, labelpad=10)
    ax.set_zlabel('Z (mm)', fontsize=10, labelpad=10)
    
    # View limits and aspect ratio
    ax.set_xlim(-10, pw + 10)
    ax.set_ylim(-10, ph + 10)
    ax.set_zlim(-pt - 5, safe_z + 2)
    
    ax.set_box_aspect((pw + 20, ph + 20, pt + safe_z + 7))  # Aspect ratio matching actual scale
    
    # Set default view angle for best 3D perspective
    ax.view_init(elev=30, azim=-60)
    
    ax.legend(loc='upper right', bbox_to_anchor=(1.15, 0.95))
    plt.tight_layout()
    
    # Create target directory if it doesn't exist
    os.makedirs(os.path.dirname(image_path), exist_ok=True)
    
    plt.savefig(image_path, bbox_inches='tight')
    plt.close()
    print(f"3D Toolpath image successfully saved to {image_path}")

if __name__ == "__main__":
    # Generate G-code
    gcode_file = generate_gcode()
    
    # Set target image path inside the artifact directory
    artifact_dir = "/Users/hiro/.gemini/antigravity/brain/c03c5648-e4cd-4777-b72a-b5e2572805e9"
    image_path = os.path.join(artifact_dir, "toolpath_3d.png")
    
    # Parse and plot toolpaths
    parse_gcode_and_plot(gcode_file, image_path)
